# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Plumb < Formula
  desc "LSP-backed MCP server with crash-safe, concurrent writes for coding agents."
  homepage "https://github.com/plumbkit/plumb"
  version "0.22.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/plumbkit/plumb/releases/download/v0.22.0/plumb_0.22.0_darwin_amd64.tar.gz"
      sha256 "197f170612cfc7f76992a04e823906e58dc3ffcbdeb1886f31aea0259a6bacab"

      define_method(:install) do
        bin.install "plumb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/plumbkit/plumb/releases/download/v0.22.0/plumb_0.22.0_darwin_arm64.tar.gz"
      sha256 "b26d859adb94cd10f0791e8075b78fc130b44f45df9cada0b990f64e9ad4aefc"

      define_method(:install) do
        bin.install "plumb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/plumbkit/plumb/releases/download/v0.22.0/plumb_0.22.0_linux_amd64.tar.gz"
      sha256 "8f0d22e1d929ad8645ce46b6c0f847b591baed7c2c68ed3faa14229b549910f8"
      define_method(:install) do
        bin.install "plumb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/plumbkit/plumb/releases/download/v0.22.0/plumb_0.22.0_linux_arm64.tar.gz"
      sha256 "27f14c8012b201474cddd9a1d989ea8845b71b4691471591f93f6ceab4aa9b59"
      define_method(:install) do
        bin.install "plumb"
      end
    end
  end

  test do
    system "#{bin}/plumb", "version"
  end
end
