# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Plumb < Formula
  desc "LSP-backed MCP server with crash-safe, concurrent writes for coding agents."
  homepage "https://github.com/plumbkit/plumb"
  version "0.17.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/plumbkit/plumb/releases/download/v0.17.0/plumb_0.17.0_darwin_amd64.tar.gz"
      sha256 "6c8fdd6701e383de253cdec0d380ba9d63d375790e4a715782010cd7597ea98c"

      define_method(:install) do
        bin.install "plumb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/plumbkit/plumb/releases/download/v0.17.0/plumb_0.17.0_darwin_arm64.tar.gz"
      sha256 "b8caaf02832123736bacf4f80e35d7388e4a6e7c82c4935cd2aa3bbf73021a85"

      define_method(:install) do
        bin.install "plumb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/plumbkit/plumb/releases/download/v0.17.0/plumb_0.17.0_linux_amd64.tar.gz"
      sha256 "bf02043f3f0889e08ef339bef414ff752688063cd59eede6e69e5f1cdb0b346c"
      define_method(:install) do
        bin.install "plumb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/plumbkit/plumb/releases/download/v0.17.0/plumb_0.17.0_linux_arm64.tar.gz"
      sha256 "4870d7155fbfd4f5311ab026aea951bd272c08b265aabffbbe6d9c61e8714677"
      define_method(:install) do
        bin.install "plumb"
      end
    end
  end

  test do
    system "#{bin}/plumb", "version"
  end
end
